### ISSUE TITLE
nodjes12 deprecated warning

### ISSUE THREAD

**Issue by Vincent-1990** [cloudflare/cloudflare-gcp#132]
pulling from latest master

WARNING: The nodejs12 runtime is deprecated on Cloud Functions. Please migrate to a newer Node.js version (--runtime=nodejs18). See https://cloud.google.com/functions/docs/migrating/nodejs-runtimes

**Comment by stiak** [comment]
I set this up on node 20 with this branch: https://github.com/cloudflare/cloudflare-gcp/pull/133
