### ISSUE TITLE
Multiple buckets in deploy.sh

### ISSUE THREAD

**Issue by splashy17** [cloudflare/cloudflare-gcp#20]
Is it possible to link multiple buckets in one deploy.sh file? Would it be something like:
BUCKET_NAME="bucketLog1", "bucketLog2", "bucketLog3"
DATASET= "logs1", "logs2", "logs3"

or would you need to create three different functions?

**Comment by shagamemnon** [comment]
Try this @splashy17:

```js
/*
 * You'll either need to run this in the Google Cloud Shell (node.js is pre-install on GCP Shell)
 * or you'll need Node.js installed on your local machine
 *
 *  Add this file in the same subdirectory as deploy.sh like:
 *  logpush-to-bigquery
 *   → deploy.sh
 *   → deploy.js (this file)
 *   → index.js
 *
 * cd logpush-to-bigquery
 * node deploy.js
*/

// deploy.sh
const config = {
  'REGION': 'us-central-1',
  'FN_NAME': 'gcsbq',
  'TABLES': [
    'cloudflare_table1', 'cloudflare_table2'
  ],
  'DATASET': [
    'cloudflare_dataset1', 'cloudflare_dataset2'
  ],
  'BUCKET_NAME': [
    'bucket1', 'bucket2'
  ]
}

module.exports = (function () {
  for (let i = 0; i < config.TABLES.length; i++) {
    const cmd = `gcloud functions deploy ${config.FN_NAME + i} --runtime nodejs8 --trigger-resource ${config.BUCKET_NAME[i]} --trigger-event google.storage.object.finalize --region=${config.REGION} --memory=1024MB --entry-point=gcsbq --set-env-vars DATASET=${config.DATASET[i]},TABLE=${config.TABLES[i]},SCHEMA=./schema.json`
    require('child_process').execSync(cmd)
  }
})()
```

**Comment by splashy17** [comment]
@shagamemnon so do you do anything with the deploy.sh file?

**Comment by splashy17** [comment]
@shagamemnon is it possible to not have the .js file and just do it within the deploy.sh file?

**Comment by shagamemnon** [comment]
I’m sure it’s possible but (unfortunately) I’m not a bash expert. You’d need to use the `jq` bash library.

Google Cloud Shell is pre-installed with node.js, so if you copy this file into the same directory as the deploy.sh file and run `node deploy.js`, you’ll be able to accomplish your goal. To be clear, you can delete the actual deploy.sh file if you use this strategy. I’m referring to it on this thread as a reference point for downloading deploy.js into the correct subdirectory
