### ISSUE TITLE
memory allocation cloud function

### ISSUE THREAD

**Issue by Eraac** [cloudflare/cloudflare-gcp#53]
Does there are any reason to set 1024MB of memory for the cloud function? On our side the function never consume more than 80MB
![image](https://user-images.githubusercontent.com/5497623/91171412-b8729f00-e6da-11ea-889c-183c9ec7fb6f.png)

Reducing the memory allocation can reduce cost, actually 1024MB is seven time expensive than 128MB. So we need to know if we can safely reduce the memory allocation

**Comment by shagamemnon** [comment]
You an safely reduce memory yes. 1024MB is set because users often use this with Pub/Sub, which requires log parsing and thus a larger heap
