### ISSUE TITLE
Support for the Firewall Events Schema

### ISSUE THREAD

**Issue by baustinceltic** [cloudflare/cloudflare-gcp#58]
Similar to PR #44 regarding the addition of the Spectrum schema, it would be nice if the firewall_events data set was an option as well. https://developers.cloudflare.com/logs/log-fields#firewall-events

**Comment by shagamemnon** [comment]
Thanks for flagging this @baustinceltic ! Yes we should do this as soon as possible. I will open a PR

**Comment by shagamemnon** [comment]
@baustinceltic do you have an active firewall events logpush job running? If so, please let me know if you can run this schema through a test.

**Comment by baustinceltic** [comment]
No, I don't currently have one running for firewall events.  I configured logpush for http-requests via the UI which is when I discovered that the firewall events schema wasn't an option in that drop down menu.
