### ISSUE TITLE
"No new logs" on all cloud function executions

### ISSUE THREAD

**Issue by andreeleuterio** [cloudflare/cloudflare-gcp#89]
Hi folks, I tried to deploy the dashboard following [these instructions](https://developers.cloudflare.com/fundamentals/data-products/analytics-integrations/google-cloud). All executions of the cloud function run successfully but give a "No new logs" output. I don't see the configured dataset in BigQuery leading me to believe it wasn't created because the function didn't find new logs.

I can see logs coming in to the bucket. I configured the `DIRECTORY` env var to `/` because the date folders are in the root of the bucket. I also see the pub sub topic and cron jobs. Any ideas on how to further debug this?

cc @mohammadualam

**Comment by shagamemnon** [comment]
Hey @andreeleuterio - can you post a few more pieces of information here to help replicate? What I need is ..

- The command in `deploy.sh`, interpolated with the actual environment variables you used
- An example URI of the log, found here: `https://console.cloud.google.com/storage/browser/_details/<BUCKET_NAME>` For example: ![screenshot.jpg](https://storage.franktaylor.io/a40d5545ab9b313238282d8dc55c33ec34a87f1b/Screenshot%2020211026T1%E2%80%A6g-cf-logs%20%E2%80%93%20Object%20details%20%E2%80%93%20Cloud%20Storage%20%E2%80%93%20Cloudflare%20SE%20Team%20%E2%80%93%20Google%20Cloud%20Platform%202021-11-17%20at%2017.09%20IyL7SATX-1.jpg)

**Comment by goaaron** [comment]
@andreeleuterio @shagamemnon  
I'm thinking it's a timestamp issue. The node function is outputting a prefix datetime that is 12 hours behind in my usage. So nothing in `bucket.getFiles` will be appear for 12 hours.

**Comment by shagamemnon** [comment]
@goaaron good catch. Thanks for pointing this out -- this is a change we'll need to make in master :)
