### ISSUE TITLE
cloudfuntions allways "no new logs at yyyyMMddTHHmm

### ISSUE THREAD

**Issue by corby1037** [cloudflare/cloudflare-gcp#90]
Hi all.

i want to using cloudflare log for gcp data studio.
but cloud funtions is allways "no new logs at yyyyMMddTHHmm"
i can't store Big Query

delpoy.sh code
```
SCHEMA="schema-http.json"
# The name of the subdirectory in your bucket used for Cloudflare Logpush logs,
# for example, "logs/". If there is no subdirectory, use "/"
DIRECTORY="/"
BUCKET_NAME="STORAGE-NAME"
DATASET="cloudflare_logstream"
TABLE="cloudflare_logs"
REGION="asia-northeast3"
# You probably don't need to change these values:
FN_NAME="cf-logs-to-bigquery"
TOPIC_NAME="every_minute"
```

Cloud Functions logs
![image](https://user-images.githubusercontent.com/3301587/146285396-1d89f9f8-0078-4ac5-aadd-0deaf5b024db.png)

Cloud Storage
![image](https://user-images.githubusercontent.com/3301587/146285648-32b67eca-c92f-46b5-be05-dc28ba28bc8b.png)

What more should I check?

**Comment by shagamemnon** [comment]
Hey @corby1037 can you provide the storage location of one of these logs in `gcs://` syntax?

**Comment by corby1037** [comment]
@shagamemnon gs://BUCKET-NAME/20211217/20211217T144120Z_20211217T144150Z_a7f0955a.log.gz

**Comment by shagamemnon** [comment]
I'm assuming that variable value `BUCKET_NAME=STORAGE-NAME` in your deploy.sh is the same value as `BUCKET-NAME` in your comment here?

**Comment by shagamemnon** [comment]
This should be fixed now. Please confirm @corby1037

**Comment by corby1037** [comment]
@shagamemnon 
i remove "/" in depoly.sh file. 
i can access my bucket :)
THX :)
